# Generated by Django 4.2.6 on 2024-01-20 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='correo',
            new_name='email',
        ),
    ]
